-- MySQL Script generated by MySQL Workbench
-- Mon Jan 16 21:13:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`distribution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`distribution` (
  `id` VARCHAR(14) NOT NULL,
  `expirationDate` DATE NULL,
  `mailingListId` VARCHAR(45) NULL,
  `description` VARCHAR(512) NULL,
  `surveyId` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participant` (
  `contactId` VARCHAR(20) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `phone_number` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`contactId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`distribution_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`distribution_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `distributionId` VARCHAR(14) NOT NULL,
  `participantId` VARCHAR(20) NOT NULL,
  `surveyLink` VARCHAR(512) NULL,
  `surveyStatus` VARCHAR(45) NULL,
  `surveyDelivered` TINYINT NULL,
  `linkExpiration` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_distribution_list_distributions_idx` (`distributionId` ASC) VISIBLE,
  INDEX `fk_distribution_list_participant1_idx` (`participantId` ASC) VISIBLE,
  CONSTRAINT `fk_distribution_list_distributions`
    FOREIGN KEY (`distributionId`)
    REFERENCES `mydb`.`distribution` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_distribution_list_participant1`
    FOREIGN KEY (`participantId`)
    REFERENCES `mydb`.`participant` (`contactId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
